name: Deploy eHospital

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /opt/eHospital2.0
            git stash
            git checkout main
            git pull origin main --rebase
            git stash pop
            docker compose up -d --build --remove-orphans
